export const SET_LOGIN_LOADING = 'SET_LOGIN_LOADING'
export const SET_LOGIN_SUCCESS = 'SET_LOGIN_SUCCESS'
export const SET_LOGIN_FAILED = 'SET_LOGIN_FAILED'
export const SET_LOGOUT_LOADING = 'SET_LOGIN_LOADING'
export const SET_LOGOUT_SUCCESS = 'SET_LOGOUT_SUCCESS'
export const SET_LOGOUT_FAILED = 'SET_LOGOUT_FAILED'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
