export const FETCH_REKAP_TALIKUAT_LOADING = 'FETCH_REKAP_TALIKUAT_LOADING'
export const FETCH_REKAP_TALIKUAT_SUCCESS = 'FETCH_REKAP_TALIKUAT_SUCCESS'
export const FETCH_REKAP_TALIKUAT_FAILED = 'FETCH_REKAP_TALIKUAT_FAILED'
