export const FETCH_REKAP_RUMIJA_LOADING = 'FETCH_REKAP_RUMIJA_LOADING'
export const FETCH_REKAP_RUMIJA_SUCCESS = 'FETCH_REKAP_RUMIJA_SUCCESS'
export const FETCH_REKAP_RUMIJA_FAILED = 'FETCH_REKAP_RUMIJA_FAILED'
