export const FETCH_REKAP_PEMELIHARAAN_LOADING =
  'FETCH_REKAP_PEMELIHARAAN_LOADING'
export const FETCH_REKAP_PEMELIHARAAN_SUCCESS =
  'FETCH_REKAP_PEMELIHARAAN_SUCCESS'
export const FETCH_REKAP_PEMELIHARAAN_FAILED = 'FETCH_REKAP_PEMELIHARAAN_FAILED'
